spring:
  aop:
    proxy-target-class: true
    auto: true
  http:
    multipart:
      maxFileSize: 10000MB
      maxRequestSize: 10000MB
  profiles:
    active: dev

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 19123
  tomcat:
    uri-encoding: utf-8
prop:
  cas-ignore-pattern: /api/.*|/account/.*|/static/.*|/project/.*|/system/.*|/evaluate/.*|/sjextract/.*|/xfjextract/.*|/special/.*|/statistics/.*|/supervision/.*|/cas/login/info|/test/.*
#pagehelper:
#  helperDialect: postgresql
#  reasonable: true
#  supportMethodsArguments: true
#  row-bounds-with-count: true
#  offset-as-page-num: true
#  page-size-zero: true
mybatis:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://172.17.118.239:5432/smp?charSet=utf-8&currentSchema=rpt
    username: smp
    password: 123456
    driver-class-name: org.postgresql.Driver
    maximumPoolSize: 30
    maxLifetime: 1800000
  redis:
    host: 172.17.118.238
    port: 6379
#logging:
#  config: classpath:logback.dev.xml
cas:
  server-url-prefix: http://172.17.118.238:8081/cas
  server-login-url: http://172.17.118.238:8081/cas/login
  client-host-url: http://localhost:19123
  validation-type: cas
  authentication-url-patterns: /cas/login/index
prop:
  redirect-url: http://localhost:8088/#/casLogin
file:
  confirm-url: http://172.17.118.238:9003/storage/confirm
---
spring:
  profiles: pro
  datasource:
    url: jdbc:postgresql://50.73.126.6:20003/szga_aqjg?charSet=utf-8&currentSchema=rpt
    username: aqjg_os
    password: Szgaos@123
    driver-class-name: org.postgresql.Driver
    maximumPoolSize: 30
    maxLifetime: 1800000
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  config: classpath:logback.pro.xml
cas:
  #Required properties
  server-url-prefix: http://tyyh.szh.js:9080/cas
  server-login-url: http://tyyh.szh.js:9080/cas/login
  client-host-url: http://50.73.70.34:19123
  validation-type: cas
  authentication-url-patterns: /cas/login/index
prop:
  redirect-url: http://50.73.70.34/#/casLogin
file:
  confirm-url: http://50.73.94.107:9003/storage/v1/confirm

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://172.17.118.239:5432/smp?charSet=utf-8&currentSchema=rpt
    username: smp
    password: 123456
    driver-class-name: org.postgresql.Driver
    maximumPoolSize: 30
    maxLifetime: 1800000
  redis:
    host: 172.17.118.238
    port: 6379
#logging:
#  config: classpath:logback.dev.xml
cas:
  server-url-prefix: http://172.17.118.238:8081/cas
  server-login-url: http://172.17.118.238:8081/cas/login
  client-host-url: http://172.17.118.238:19123
  validation-type: cas
  authentication-url-patterns: /cas/login/index
prop:
  redirect-url: http://172.17.118.238:8011/#/casLogin
file:
  confirm-url: http://172.17.118.238:9003/storage/confirm