###示例接口1

POST {{baseUrl}}/test
Accept: */*
Content-Type: application/x-www-form-urlencoded

type=aa

###示例接口2

POST {{baseUrl}}/test3
Content-Type: application/json

{
  "key": "value"
}


###示例接口3

GET {{baseUrl}}/test2

#> {% client.global.set("auth_token",response.body.json.token); %}
###


GET http://localhost:19123/flow/report/page
Accept: application/json

###

POST http://localhost:19123/wxpfx/wxjs
Content-Type: application/json

{}

###